name: Test VSCode Download
on: [push]

jobs:
  download-vscode:
    # ⬇️ ВОТ ЗДЕСЬ ВЫБИРАЕТСЯ ОС
    runs-on: windows-latest        # Windows Server 2022
    # runs-on: windows-2022        # Windows Server 2022
    # runs-on: windows-2019        # Windows Server 2019
    
    steps:
      - name: Download VSCode
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://update.code.visualstudio.com/latest/win32-x64-user/stable" -OutFile "$env:TEMP\VSCode.exe"
          Write-Host "Downloaded to $env:TEMP\VSCode.exe"
